### ISSUE TITLE
Demo: got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by mikebridge** [authorizon/fastapi_websocket_pubsub#16]
I am trying the example out on Python 3.8.5 and getting the following error when invoking the `/trigger` endpoint:

```
$ PORT=8004 python pubsub_broadcaster_server_example.py 
INFO:     Started server process [58697]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8004 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 37088) - "WebSocket /pubsub" [accepted]
INFO:     127.0.0.1:37124 - "GET /trigger/ HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:37124 - "GET /trigger HTTP/1.1" 200 OK
Failed to notify subscriber sub_id=a8fd8a8aaf6d42238d6bda98f193bf40 with topic=germs
Traceback (most recent call last):
  File "/home/bridge/venv/websocket/lib/python3.8/site-packages/fastapi_websocket_pubsub/event_notifier.py", line 156, in callback_subscribers
    await self.trigger_callback(data, topic, subscriber_id, event)
  File "/home/bridge/venv/websocket/lib/python3.8/site-packages/fastapi_websocket_pubsub/event_notifier.py", line 129, in trigger_callback
    await subscription.callback(subscription, data)
  File "/home/bridge/venv/websocket/lib/python3.8/site-packages/fastapi_websocket_pubsub/event_broadcaster.py", line 157, in __broadcast_notifications__
    async with self._publish_lock:
  File "/usr/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.8/asyncio/locks.py", line 203, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-20' coro=<EventNotifier.callback_subscribers() running at /home/bridge/venv/websocket/lib/python3.8/site-packages/fastapi_websocket_pubsub/event_notifier.py:156> cb=[gather.<locals>._done_callback() at /usr/lib/python3.8/asyncio/tasks.py:758]> got Future <Future pending> attached to a different loop
INFO:     ('127.0.0.1', 37644) - "WebSocket /pubsub" [accepted]
```

The client does see the events though:

```
$ PORT=8004 python pubsub_client_example.py 
running callback for guns!
running callback for germs!
running callback for germs!
running callback steel!
Got data None
```

This what I have installed:
```
aiohttp==3.7.4.post0
async-timeout==3.0.1
asyncpg==0.22.0
attrs==20.3.0
broadcaster==0.2.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
fastapi==0.63.0
fastapi-websocket-pubsub==0.1.17
fastapi-websocket-rpc==0.1.18
flake8==3.9.0
h11==0.12.0
idna==2.10
iniconfig==1.1.1
mccabe==0.6.1
multidict==5.1.0
packaging==20.9
pkg-resources==0.0.0
pluggy==0.13.1
py==1.10.0
pycodestyle==2.7.0
pydantic==1.8.1
pyflakes==2.3.1
PyJWT==2.0.1
pyparsing==2.4.7
pytest==6.2.3
requests==2.25.1
sentry-sdk==1.0.0
six==1.15.0
starlette==0.13.6
tenacity==7.0.0
toml==0.10.2
typing-extensions==3.7.4.3
urllib3==1.26.4
uvicorn==0.13.4
websockets==8.1
yarl==1.6.3
```

**Comment by orweis** [comment]
Hi @mikebridge, 
Thanks for reporting this!
I believe you have found a bug in the recent released version (a silly mistake as well - initing 
self._publish_lock in __init__ instead of within the with statement).

I'll create and deploy a new version soon, meanwhile feel free to use the previous version (0.1.16)

**Comment by orweis** [comment]
Hi @mikebridge - check out [0.1.18](https://pypi.org/project/fastapi-websocket-pubsub/0.1.18/) 
Should resolve this issue ;-)

**Comment by mikebridge** [comment]
@orweis Great, thant seems to work, thanks!
